# Config file for Air
[build]
cmd = "go run cmd/main.go"
bin = "tmp/main"
full_bin = "false"
# Directory where Air will execute the command
working_dir = "."
# Ignore folders or files
include_ext = ["go", "tpl", "tmpl", "html"]
exclude_dir = ["vendor", "node_modules", "static"]

# Watching directories and files
[log]
level = "debug"

[runner]
output_on_rebuild = true
